package com.example.openapiex04

data class MsrstnInfoInqireSvrVo(
    val _returnType: String,
    val addr: String,
    val districtNum: String,
    val dmX: String,
    val dmY: String,
    val item: String,
    val mangName: String,
    val map: String,
    val numOfRows: String,
    val oper: String,
    val pageNo: String,
    val photo: String,
    val resultCode: String,
    val resultMsg: String,
    val rnum: Int,
    val serviceKey: String,
    val sggName: String,
    val sidoName: String,
    val stationCode: String,
    val stationName: String,
    val tm: Int,
    val tmX: String,
    val tmY: String,
    val totalCount: String,
    val umdName: String,
    val ver: String,
    val vrml: String,
    val year: String
)